apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development
spec:
  type: NodePort
  ports:
    - targetPort: 4000
      port: 8080
      nodePort: 30097
  selector:
     run: jekyll
